### ISSUE TITLE
trying install

### ISSUE THREAD

**Issue by kalashnikovisme** [wakatime/gedit-wakatime#1]
Ubuntu 14.04

``` shell
sudo python ~/gedit-wakatime-master/install.py 
Traceback (most recent call last):
  File "/home/username/gedit-wakatime-master/install.py", line 38, in <module>
    except PermissionError:
NameError: name 'PermissionError' is not defined
```

What should I do?

**Comment by alanhamlett** [comment]
The new `install.py` should work.

**Comment by kalashnikovisme** [comment]
@alanhamlett new problem

``` shell
sudo python ~/gedit-wakatime-master/install.py 
Traceback (most recent call last):
  File "/home/username/gedit-wakatime-master/install.py", line 47, in <module>
    install()
  File "/home/username/gedit-wakatime-master/install.py", line 36, in install
    check_wakatime()
  File "/home/username/gedit-wakatime-master/install.py", line 31, in check_wakatime
    import pip
ImportError: No module named pip

```

**Comment by alanhamlett** [comment]
Install pip (https://pip.pypa.io/en/latest/installing.html) then run `install.py` again.

**Comment by kalashnikovisme** [comment]
@alanhamlett everything works. thnx. Please, update Readme with installation pip, or include pip-installation into `install.py`.

**Comment by mzuniga** [comment]
Hi  @alanhamlett  I had a problem:

# python install.py

Traceback (most recent call last):
  File "install.py", line 47, in <module>
    install()
  File "install.py", line 36, in install
    check_wakatime()
  File "install.py", line 31, in check_wakatime
    import pip
  File "/usr/lib/python2.7/site-packages/pip/**init**.py", line 12, in <module>
    from pip.commands import commands, get_similar_commands, get_summaries
  File "/usr/lib/python2.7/site-packages/pip/commands/**init**.py", line 6, in <module>
    from pip.commands.bundle import BundleCommand
  File "/usr/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>
    from pip.commands.install import InstallCommand
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>
    from pip.req import InstallRequirement, RequirementSet, parse_requirements
  File "/usr/lib/python2.7/site-packages/pip/req/**init**.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 24, in <module>
    from pip.exceptions import (
ImportError: cannot import name UnsupportedWheel

Thanks in advance!

**Comment by shivdhwaj** [comment]
Ubuntu 16.04 same issue

> Traceback (most recent call last):
>   File "/home/username/gedit-wakatime-master/install.py", line 38, in <module>
>     except PermissionError:
